# Generated by Django 5.0.1 on 2026-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='crop_type',
            field=models.CharField(choices=[('sugarcane', 'Sugarcane'), ('grapes', 'Grapes')], default='sugarcane', help_text='Select the crop type for this Industry', max_length=50),
        ),
    ]
