# Generated by Django 5.0.1 on 2025-11-18 08:18
# Modified to fix phone number duplicates before applying unique constraint

from django.db import migrations, models


def fix_phone_numbers_before_unique(apps, schema_editor):
    """Fix phone numbers before applying unique constraint"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Make column nullable if it's not already
        cursor.execute("""
            SELECT is_nullable 
            FROM information_schema.columns
            WHERE table_name = 'users_user' 
            AND column_name = 'phone_number';
        """)
        result = cursor.fetchone()
        if result and result[0] == 'NO':
            cursor.execute("""
                ALTER TABLE users_user 
                ALTER COLUMN phone_number DROP NOT NULL;
            """)
        
        # Step 2: Convert empty strings to NULL
        cursor.execute("""
            UPDATE users_user
            SET phone_number = NULL
            WHERE phone_number = '' OR TRIM(phone_number) = '';
        """)
        
        # Step 3: Find and fix duplicates (non-NULL)
        cursor.execute("""
            SELECT phone_number, COUNT(*) as count
            FROM users_user
            WHERE phone_number IS NOT NULL 
            AND phone_number != ''
            GROUP BY phone_number
            HAVING COUNT(*) > 1;
        """)
        duplicates = cursor.fetchall()
        
        for phone, count in duplicates:
            # Get all user IDs with this phone, keep first (by ID), set others to NULL
            cursor.execute("""
                SELECT id FROM users_user
                WHERE phone_number = %s
                ORDER BY id;
            """, (phone,))
            user_ids = [row[0] for row in cursor.fetchall()]
            
            # Set all except first to NULL
            if len(user_ids) > 1:
                cursor.execute("""
                    UPDATE users_user
                    SET phone_number = NULL
                    WHERE id = ANY(%s) AND id != %s;
                """, (user_ids, user_ids[0]))
        
        # Step 4: Drop existing unique constraints/indexes if they exist
        # Safe to use names from database directly, but validate they only contain safe chars
        import re
        
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints
            WHERE table_name = 'users_user'
            AND constraint_type = 'UNIQUE'
            AND constraint_name LIKE '%phone%';
        """)
        constraints = [row[0] for row in cursor.fetchall()]
        for constraint in constraints:
            # Validate constraint name contains only safe characters
            if re.match(r'^[a-zA-Z0-9_]+$', constraint):
                cursor.execute(f"""
                    ALTER TABLE users_user 
                    DROP CONSTRAINT IF EXISTS "{constraint}";
                """)
        
        # Drop indexes
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'users_user'
            AND indexname LIKE '%phone%';
        """)
        indexes = [row[0] for row in cursor.fetchall()]
        for index in indexes:
            # Validate index name contains only safe characters
            if re.match(r'^[a-zA-Z0-9_]+$', index):
                cursor.execute(f'DROP INDEX IF EXISTS "{index}";')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_default_industry'),
    ]

    operations = [
        # Fix phone numbers before applying unique constraint
        migrations.RunPython(
            fix_phone_numbers_before_unique,
            migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (10 digits for India). Optional.', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True),
        ),
    ]
