# Generated by Django 5.0.1 on 2025-11-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_industry_test_password_industry_test_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('api_request', 'API Request'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('error', 'Error')], default='api_request', help_text='Type of action performed', max_length=20)),
                ('endpoint', models.CharField(help_text='API endpoint or URL accessed', max_length=500)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('request_data', models.JSONField(blank=True, help_text='Request payload/data (sanitized)', null=True)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent/browser information', max_length=500)),
                ('message', models.TextField(blank=True, help_text='Additional message or error details')),
                ('is_success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(blank=True, help_text='Industry context for this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='users.industry')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frontend Activity Log',
                'verbose_name_plural': 'Frontend Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_front_created_0be6aa_idx'), models.Index(fields=['user', '-created_at'], name='users_front_user_id_722a7d_idx'), models.Index(fields=['industry', '-created_at'], name='users_front_industr_e9c46a_idx'), models.Index(fields=['action_type', '-created_at'], name='users_front_action__02eedd_idx')],
            },
        ),
    ]
