# Generated by Django 5.0.1 on 2025-11-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_frontendactivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendActivityLog',
        ),
    ]
