services:
  web:
    build: .
    container_name: cropeye_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
    restart: unless-stopped
