# Generated by Django 5.0.1 on 2025-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_e_status_fb8540_idx',
            old_name='equipment_e_status_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_e_assigne_96ad0d_idx',
            old_name='equipment_e_assigne_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_e_locatio_e2f5a2_idx',
            old_name='equipment_e_locatio_8b5b0a_idx',
        ),
    ]
