# Generated by Django 5.0.1 on 2026-02-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['assigned_to'], name='equipment_e_assigne_96ad0d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['location'], name='equipment_e_locatio_e2f5a2_idx'),
        ),
    ]
