# Generated by Django 5.0.1 on 2025-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='llama3.1', help_text='Ollama model name to use', max_length=100)),
                ('api_url', models.URLField(default='http://localhost:11434/api/generate', help_text='Ollama API endpoint URL')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable chatbot service')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
