# Generated by Django 5.0.1 on 2026-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('tools', 'Tools'), ('equipment', 'Equipment'), ('feed', 'Animal Feed'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired')], default='in_stock', max_length=20)),
                ('reorder_level', models.IntegerField(default=0, help_text='Minimum quantity before reorder is needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('item_type', models.CharField(choices=[('logistic', 'Logistic'), ('transport', 'Transport'), ('equipment', 'Equipment'), ('office_purpose', 'Office Purpose'), ('storage', 'Storage'), ('processing', 'Processing')], default='logistic', max_length=50, verbose_name='Item Type')),
                ('make', models.CharField(blank=True, max_length=200, verbose_name='Make')),
                ('year_of_make', models.CharField(blank=True, max_length=10, null=True, verbose_name='Year of Make')),
                ('estimate_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimate Cost')),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not working'), ('under_repair', 'underRepair')], default='working', max_length=20, verbose_name='Status')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-created_at'],
            },
        ),
    ]
