# Generated by Django 5.0.1 on 2026-02-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this inventory item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.industry'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this stock item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.industry'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status'], name='inventory_i_status_77888d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item_type'], name='inventory_s_item_ty_96d067_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['status'], name='inventory_s_status_7ad998_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item_name'], name='inventory_s_item_na_35c454_idx'),
        ),
    ]
