# Generated by Django 5.0.1 on 2025-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assign_industry_to_existing_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_categor_fe6a79_idx',
            old_name='inventory_in_categor_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_status_77888d_idx',
            old_name='inventory_in_status_8b5b0a_idx',
        ),
    ]
