# Generated by Django 5.0.1 on 2025-11-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_create_stock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='inventory_s_item_ty_96d067_idx',
            old_name='inventory_s_item_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='inventory_s_status_7ad998_idx',
            old_name='inventory_s_status_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='inventory_s_item_na_35c454_idx',
            old_name='inventory_s_item_na_idx',
        ),
    ]
