# Generated by Django 5.0.1 on 2025-11-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_assign_industry_to_existing_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_4a0a95_idx',
            old_name='tasks_task_status_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_a900d4_idx',
            old_name='tasks_task_priorit_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_ab55af_idx',
            old_name='tasks_task_assigne_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_bce847_idx',
            old_name='tasks_task_due_dat_8b5b0a_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
