# Generated by Django 5.0.1 on 2026-03-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_notification_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='tasks_notif_user_id_23b12d_idx',
            old_name='tasks_notification_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tasks_notif_user_id_9ee72a_idx',
            old_name='tasks_notification_user_read_idx',
        ),
    ]
