# Generated by Django 5.0.1 on 2025-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='vendors_pur_status_9a5992_idx',
            old_name='vendors_purch_status_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='vendors_pur_issue_d_abb2fe_idx',
            old_name='vendors_purch_issue_d_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='vendors_pur_expecte_d9c75b_idx',
            old_name='vendors_purch_expecte_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_vendor__150aec_idx',
            old_name='vendors_vendo_vendor__8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_rating_1e84ed_idx',
            old_name='vendors_vendo_rating_8b5b0a_idx',
        ),
    ]
