# Generated by Django 5.0.1 on 2025-11-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_add_accounting_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['item_name', 'inventory_item__item_name']},
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_gstin_n_a970a3_idx',
            old_name='vendors_ven_gstin_n_123abc_idx',
        ),
    ]
