# Generated by Django 5.0.1 on 2025-11-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_create_order_and_orderitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='vendors_ord_invoice_4bc631_idx',
            old_name='vendors_ord_invoice__idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='vendors_ord_invoice_44abbe_idx',
            old_name='vendors_ord_invoice__idx2',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='vendors_ord_state_a075ae_idx',
            old_name='vendors_ord_state_idx',
        ),
    ]
