# Generated by Django 5.0.1 on 2026-02-05 15:17

import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, help_text='Name of the crop type', max_length=100)),
                ('plantation_type', models.CharField(blank=True, choices=[('adsali', 'Adsali'), ('suru', 'Suru'), ('ratoon', 'Ratoon'), ('pre-seasonal', 'Pre-Seasonal'), ('post-seasonal', 'Post-Seasonal'), ('pre_seasonal', 'Pre-Seasonal'), ('other', 'Other')], help_text='Plantation type for this crop', max_length=100)),
                ('planting_method', models.CharField(blank=True, choices=[('3_bud', '3 Bud Method'), ('2_bud', '2 Bud Method'), ('1_bud', '1 Bud Method'), ('1_bud_stip_Method', '1 Bud (stip Method)'), ('other', 'Other')], help_text='Planting method for this crop', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop Type',
                'verbose_name_plural': 'Crop Types',
                'ordering': ['crop_type'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.TextField()),
                ('area_size', models.DecimalField(decimal_places=2, help_text='Size in acres', max_digits=10)),
                ('farm_document', models.FileField(blank=True, null=True, upload_to='farm_documents/')),
                ('plantation_date', models.DateField(blank=True, help_text='Date when crops were planted', null=True)),
                ('spacing_a', models.DecimalField(blank=True, decimal_places=2, help_text='Spacing A in meters', max_digits=8, null=True)),
                ('spacing_b', models.DecimalField(blank=True, decimal_places=2, help_text='Spacing B in meters', max_digits=8, null=True)),
                ('crop_variety', models.CharField(blank=True, help_text='Crop variety (e.g., Co 86032, Co 8371, etc.)', max_length=200, null=True)),
                ('sugarcane_plantation_type', models.CharField(blank=True, choices=[('', '---------'), ('adsali', 'Adsali'), ('suru', 'Suru'), ('ratoon', 'Ratoon'), ('pre-seasonal', 'Pre-Seasonal'), ('post-seasonal', 'Post-Seasonal'), ('pre_seasonal', 'Pre-Seasonal'), ('other', 'Other')], max_length=20, null=True)),
                ('sugarcane_planting_method', models.CharField(blank=True, choices=[('', '---------'), ('3_bud', '3 Bud Method'), ('2_bud', '2 Bud Method'), ('1_bud', '1 Bud Method'), ('1_bud_stip_Method', '1 Bud (stip Method)'), ('other', 'Other')], max_length=30, null=True)),
                ('grapes_plantation_type', models.CharField(blank=True, choices=[('', '---------'), ('wine', 'Wine Grapes'), ('table', 'Table Grapes'), ('late', 'Late'), ('early', 'Early'), ('pre_season', 'Pre-Season'), ('seasonal', 'Seasonal')], max_length=20, null=True)),
                ('variety_type', models.CharField(blank=True, choices=[('pre_season', 'Pre-season'), ('seasonal', 'Seasonal')], max_length=20, null=True)),
                ('variety_subtype', models.CharField(blank=True, choices=[('wine_grapes', 'Wine Grapes'), ('table_grapes', 'Table Grapes')], max_length=20, null=True)),
                ('variety_timing', models.CharField(blank=True, choices=[('early', 'Early'), ('late', 'Late')], max_length=10, null=True)),
                ('plant_age', models.CharField(blank=True, choices=[('0_2', '0-2 years'), ('2_3', '2-3 years'), ('above_3', 'Above 3 years')], max_length=10, null=True)),
                ('foundation_pruning_date', models.DateField(blank=True, help_text='Foundation pruning date (Grapes only)', null=True)),
                ('fruit_pruning_date', models.DateField(blank=True, help_text='Fruit pruning date (Grapes only)', null=True)),
                ('last_harvesting_date', models.DateField(blank=True, help_text='Last harvesting date (Grapes only)', null=True)),
                ('resting_period_days', models.IntegerField(blank=True, help_text='Resting period in days (Grapes only)', null=True)),
                ('row_spacing', models.DecimalField(blank=True, decimal_places=2, help_text='Row spacing in meters (Grapes drip irrigation)', max_digits=8, null=True)),
                ('plant_spacing', models.DecimalField(blank=True, decimal_places=2, help_text='Plant spacing in meters (Grapes drip irrigation)', max_digits=8, null=True)),
                ('flow_rate_liter_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Flow rate in liters/hour (Grapes drip irrigation)', max_digits=10, null=True)),
                ('emitters_per_plant', models.IntegerField(blank=True, help_text='Number of emitters per plant (Grapes drip irrigation)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('motor_horsepower', models.FloatField(blank=True, null=True)),
                ('pipe_width_inches', models.FloatField(blank=True, null=True)),
                ('distance_motor_to_plot_m', models.FloatField(blank=True, null=True)),
                ('plants_per_acre', models.IntegerField(blank=True, null=True)),
                ('flow_rate_lph', models.FloatField(blank=True, null=True)),
                ('emitters_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FarmSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrapseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('residue', 'Residue Analysis'), ('variety', 'Variety Identification'), ('soil', 'Soil Report')], max_length=20)),
                ('file', models.FileField(upload_to='plot_files/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler Irrigation'), ('flood', 'Flood Irrigation'), ('center_pivot', 'Center Pivot Irrigation'), ('manual', 'Manual Irrigation'), ('none', 'None')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plantation type name (e.g., Adsali, Suru, Kharif)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code for this plantation type (used in CropType.plantation_type field)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this plantation type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plantation type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Planting method name (e.g., 3 Bud Method, Broadcast)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code for this planting method (used in CropType.planting_method field)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this planting method')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this planting method is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gat_number', models.CharField(max_length=50)),
                ('plot_number', models.CharField(blank=True, max_length=50)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('taluka', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('soil_moisture', 'Soil Moisture'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('rainfall', 'Rainfall'), ('wind', 'Wind'), ('light', 'Light'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
