# Generated by Django 5.0.1 on 2026-02-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this crop type belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_types', to='users.industry'),
        ),
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.croptype'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this farm belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.industry'),
        ),
        migrations.AddField(
            model_name='farmimage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='farmimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmirrigation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='farmsensor',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='grapsereport',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_officer_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grapsereport',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmirrigation',
            name='irrigation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.irrigationtype'),
        ),
        migrations.AddField(
            model_name='plantationtype',
            name='crop_type',
            field=models.ForeignKey(blank=True, help_text='Crop type this plantation type belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantation_types', to='farms.croptype'),
        ),
        migrations.AddField(
            model_name='plantationtype',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this plantation type belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantation_types', to='users.industry'),
        ),
        migrations.AddField(
            model_name='plantingmethod',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this planting method belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_methods', to='users.industry'),
        ),
        migrations.AddField(
            model_name='plantingmethod',
            name='plantation_type',
            field=models.ForeignKey(blank=True, help_text='Plantation type this planting method belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_methods', to='farms.plantationtype'),
        ),
        migrations.AddField(
            model_name='plot',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Field officer who created this plot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer who owns this plot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry this plot belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='users.industry'),
        ),
        migrations.AddField(
            model_name='grapsereport',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='farms.plot'),
        ),
        migrations.AddField(
            model_name='farm',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='farms.plot'),
        ),
        migrations.AddField(
            model_name='farmsensor',
            name='sensor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.sensortype'),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.soiltype'),
        ),
        migrations.AlterUniqueTogether(
            name='plantationtype',
            unique_together={('crop_type', 'industry', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='plantingmethod',
            unique_together={('plantation_type', 'industry', 'code')},
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['gat_number', 'plot_number'], name='farms_plot_gat_num_653494_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('gat_number', 'plot_number', 'village', 'taluka', 'district')},
        ),
    ]
