# Generated by Django 5.0.1 on 2026-02-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='grapes_plantation_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sugarcane_plantation_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sugarcane_planting_method',
        ),
    ]
