# Generated by Django 5.0.1 on 2025-11-19 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_assign_industry_to_existing_data'),
        ('users', '0005_industry_test_password_industry_test_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['gat_number', 'plot_number'], name='farms_plot_gat_num_653494_idx'),
        ),
    ]
