# Generated by Django 5.0.1 on 2026-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_remove_farm_grapes_plantation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='plantation_date',
        ),
        migrations.AddField(
            model_name='croptype',
            name='plantation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
