# Generated by Django 5.0.1 on 2026-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_remove_farm_plantation_date_croptype_plantation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='plantation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
