# Generated by Django 5.0.1 on 2026-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_plantation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='grape_soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy_loam', 'Sandy Loam'), ('sandy', 'Sandy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='grape_variety',
            field=models.CharField(blank=True, choices=[('thompson', 'Thompson'), ('tas_a_ganesh', 'Tas-A-Ganesh'), ('sonaka', 'Sonaka'), ('manik_chaman', 'Manik Chaman'), ('flame_seedless', 'Flame Seedless'), ('crimson_seedless', 'Crimson Seedless'), ('red_globe', 'Red Globe'), ('sudhakar_seedless', 'Sudhakar Seedless'), ('allison', 'Allison'), ('timco', 'Timco'), ('ard_35', 'ARD-35'), ('ard_36', 'ARD-36')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('drip', 'Drip'), ('flood', 'Flood')], max_length=10, null=True),
        ),
    ]
