# Generated by Django 5.2.8 on 2025-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_change_croptype_to_foreignkey'),
        ('users', '0007_delete_frontendactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptype',
            options={'ordering': ['crop_type'], 'verbose_name': 'Crop Type', 'verbose_name_plural': 'Crop Types'},
        ),
        migrations.AlterField(
            model_name='croptype',
            name='crop_type',
            field=models.CharField(blank=True, help_text='Name of the crop type', max_length=100),
        ),
        # Note: unique_together constraints for PlantationType and PlantingMethod
        # are already defined in migration 0005, so we don't need to alter them here
    ]
