# Generated by Django 5.0.1 on 2026-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_grape_soil_type_farm_grape_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='intercropping',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='new_foundation_pruning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='new_fruit_pruning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='new_last_harvesting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='new_plantation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
