# Generated by Django 5.0.1 on 2026-02-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_farm_intercropping_farm_new_foundation_pruning_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CEC')),
                ('organic_carbon', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bulk_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fe', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fe')),
                ('soil_organic_carbon', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_report', to='farms.farm')),
            ],
        ),
    ]
