# Generated by Django 5.2.8 on 2025-12-08 04:46

from django.db import migrations
from django.utils import timezone


def populate_timestamps(apps, schema_editor):
    """Populate NULL created_at and updated_at values with current timestamp"""
    CropType = apps.get_model('farms', 'CropType')
    now = timezone.now()
    
    # Update all records with NULL created_at or updated_at
    CropType.objects.filter(created_at__isnull=True).update(created_at=now)
    CropType.objects.filter(updated_at__isnull=True).update(updated_at=now)


def reverse_populate_timestamps(apps, schema_editor):
    """Reverse migration - set timestamps back to NULL (not really needed, but good practice)"""
    # This is a no-op since we can't reliably determine which values were originally NULL
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_croptype_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_timestamps, reverse_populate_timestamps),
    ]
