# Generated by Django 5.2.8 on 2025-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_populate_croptype_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
