# Generated by Django 5.0.1 on 2026-02-11 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_soilreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilreport',
            name='bulk_density',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='cec',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='organic_carbon',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='soil_organic_carbon',
        ),
        migrations.AddField(
            model_name='soilreport',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilreport',
            name='moisture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='odor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='organic_matter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='salinity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='texture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='soilreport',
            name='nitrogen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilreport',
            name='phosphorus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilreport',
            name='potassium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soilreport',
            name='soil_ph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
