# Generated by Django 5.0.1 on 2026-02-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_remove_soilreport_bulk_density_remove_soilreport_cec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='updated_at',
        ),
    ]
