# Generated by Django 5.2.8 on 2025-12-08 05:34

from django.db import migrations


def remove_constraints_if_exists(apps, schema_editor):
    """Remove constraints only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        # Remove constraint for PlantationType if it exists
        cursor.execute("""
            ALTER TABLE farms_plantationtype 
            DROP CONSTRAINT IF EXISTS farms_plantationtype_crop_industry_code_unique
        """)
        # Remove constraint for PlantingMethod if it exists
        cursor.execute("""
            ALTER TABLE farms_plantingmethod 
            DROP CONSTRAINT IF EXISTS farms_plantingmethod_plantation_industry_code_unique
        """)


def check_and_create_unique_together(apps, schema_editor):
    """Check if columns exist before creating unique_together constraints"""
    with schema_editor.connection.cursor() as cursor:
        # Check if crop_type_id column exists in farms_plantationtype
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'farms_plantationtype' 
            AND column_name = 'crop_type_id'
        """)
        plantation_type_has_column = cursor.fetchone() is not None
        
        # Check if plantation_type_id column exists in farms_plantingmethod
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'farms_plantingmethod' 
            AND column_name = 'plantation_type_id'
        """)
        planting_method_has_column = cursor.fetchone() is not None
        
        # Create unique constraints only if columns exist
        if plantation_type_has_column:
            cursor.execute("""
                ALTER TABLE farms_plantationtype 
                ADD CONSTRAINT farms_plantationtype_crop_industry_code_unique 
                UNIQUE (crop_type_id, industry_id, code)
            """)
        
        if planting_method_has_column:
            cursor.execute("""
                ALTER TABLE farms_plantingmethod 
                ADD CONSTRAINT farms_plantingmethod_plantation_industry_code_unique 
                UNIQUE (plantation_type_id, industry_id, code)
            """)


def reverse_create_unique_together(apps, schema_editor):
    """Reverse migration - remove constraints"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE farms_plantationtype 
            DROP CONSTRAINT IF EXISTS farms_plantationtype_crop_industry_code_unique
        """)
        cursor.execute("""
            ALTER TABLE farms_plantingmethod 
            DROP CONSTRAINT IF EXISTS farms_plantingmethod_plantation_industry_code_unique
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_croptype_created_at_alter_croptype_updated_at'),
        ('users', '0007_delete_frontendactivitylog'),
    ]

    operations = [
        migrations.RunPython(remove_constraints_if_exists, migrations.RunPython.noop),
        migrations.RunPython(check_and_create_unique_together, reverse_create_unique_together),
    ]
