# Generated by Django 5.0.1 on 2026-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_remove_soilreport_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilreport',
            name='color',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='odor',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='organic_matter',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='other_notes',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='salinity',
        ),
        migrations.RemoveField(
            model_name='soilreport',
            name='texture',
        ),
        migrations.AddField(
            model_name='soilreport',
            name='bulk_density',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='cec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='fe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='organic_carbon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilreport',
            name='soil_organic_carbon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
