# Generated by Django 5.2.8 on 2025-12-08 05:44

from django.db import migrations


def safe_remove_and_create_constraints(apps, schema_editor):
    """Safely remove constraints and create unique_together if columns exist"""
    with schema_editor.connection.cursor() as cursor:
        # Remove constraints if they exist
        cursor.execute("""
            ALTER TABLE farms_plantationtype 
            DROP CONSTRAINT IF EXISTS farms_plantationtype_crop_industry_code_unique
        """)
        cursor.execute("""
            ALTER TABLE farms_plantingmethod 
            DROP CONSTRAINT IF EXISTS farms_plantingmethod_plantation_industry_code_unique
        """)
        
        # Check if crop_type_id column exists in farms_plantationtype
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'farms_plantationtype' 
            AND column_name = 'crop_type_id'
        """)
        plantation_type_has_column = cursor.fetchone() is not None
        
        # Check if plantation_type_id column exists in farms_plantingmethod
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'farms_plantingmethod' 
            AND column_name = 'plantation_type_id'
        """)
        planting_method_has_column = cursor.fetchone() is not None
        
        # Create unique constraints only if columns exist
        if plantation_type_has_column:
            # Check if constraint already exists before creating
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = 'farms_plantationtype' 
                AND constraint_name = 'farms_plantationtype_crop_industry_code_unique'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE farms_plantationtype 
                    ADD CONSTRAINT farms_plantationtype_crop_industry_code_unique 
                    UNIQUE (crop_type_id, industry_id, code)
                """)
        
        if planting_method_has_column:
            # Check if constraint already exists before creating
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = 'farms_plantingmethod' 
                AND constraint_name = 'farms_plantingmethod_plantation_industry_code_unique'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE farms_plantingmethod 
                    ADD CONSTRAINT farms_plantingmethod_plantation_industry_code_unique 
                    UNIQUE (plantation_type_id, industry_id, code)
                """)


def reverse_constraints(apps, schema_editor):
    """Reverse migration - remove constraints"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE farms_plantationtype 
            DROP CONSTRAINT IF EXISTS farms_plantationtype_crop_industry_code_unique
        """)
        cursor.execute("""
            ALTER TABLE farms_plantingmethod 
            DROP CONSTRAINT IF EXISTS farms_plantingmethod_plantation_industry_code_unique
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_remove_plantationtype_farms_plantationtype_crop_industry_code_unique_and_more'),
        ('users', '0007_delete_frontendactivitylog'),
    ]

    operations = [
        migrations.RunPython(safe_remove_and_create_constraints, reverse_constraints),
    ]
