# Generated by Django 5.2.8 on 2025-12-08 05:46
# This migration uses SeparateDatabaseAndState to sync Django's migration state
# without running database operations (already handled in 0010 and 0011)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_remove_plantationtype_farms_plantationtype_crop_industry_code_unique_and_more'),
        ('users', '0007_delete_frontendactivitylog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: no-op (already handled in previous migrations)
            database_operations=[],
            # State operations: update Django's migration state
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='plantationtype',
                    unique_together={('crop_type', 'industry', 'code')},
                ),
                migrations.AlterUniqueTogether(
                    name='plantingmethod',
                    unique_together={('plantation_type', 'industry', 'code')},
                ),
            ],
        ),
    ]
