# Generated by Django 5.0.1 on 2026-02-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_remove_soilreport_color_remove_soilreport_moisture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='grape_soil_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='grape_variety',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='intercropping',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='irrigation_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='new_foundation_pruning_date',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='new_fruit_pruning_date',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='new_last_harvesting_date',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='new_plantation_date',
        ),
        migrations.AlterField(
            model_name='farm',
            name='plant_age',
            field=models.CharField(blank=True, choices=[('0_2', '0-2 years'), ('2_13', '2-13 years')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PlantationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_date', models.DateField()),
                ('grafting_date', models.DateField()),
                ('rootstock', models.CharField(choices=[('dogridge', 'Dogridge'), ('bangalore', 'Bangalore'), ('polso', 'Polso')], max_length=30)),
                ('grafted_variety', models.CharField(choices=[('thompson', 'Thompson'), ('tas_a_ganesh', 'Tas-A-Ganesh'), ('sonaka', 'Sonaka'), ('manik_chaman', 'Manik Chaman'), ('flame_seedless', 'Flame Seedless'), ('crimson_seedless', 'Crimson Seedless'), ('red_globe', 'Red Globe'), ('sudhakar_seedless', 'Sudhakar Seedless'), ('allison', 'Allison'), ('timco', 'Timco'), ('ard_35', 'ARD-35'), ('ard_36', 'ARD-36')], max_length=30)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy_loam', 'Sandy Loam'), ('sandy', 'Sandy')], max_length=30)),
                ('irrigation_type', models.CharField(choices=[('drip', 'Drip'), ('flood', 'Flood')], max_length=20)),
                ('foundation_pruning_date', models.DateField()),
                ('fruit_pruning_date', models.DateField()),
                ('source_type', models.CharField(default='new', editable=False, max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
