# Generated by Django 5.0.1 on 2026-02-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0012_remove_farm_grape_soil_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plantationrecord',
            name='intercropping',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plantationrecord',
            name='last_harvesting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantationrecord',
            name='source_type',
            field=models.CharField(choices=[('new', 'New Plantation'), ('registration', 'Registration')], editable=False, max_length=20),
        ),
    ]
