# Generated by Django 5.2.8 on 2025-12-08 05:47
# This migration uses SeparateDatabaseAndState to remove constraints from Django's state
# Database operations already handled conditionally in migrations 0010 and 0011

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0012_remove_plantationtype_farms_plantationtype_crop_industry_code_unique_and_more'),
        ('users', '0007_delete_frontendactivitylog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: no-op (already handled in previous migrations)
            database_operations=[],
            # State operations: remove constraints from Django's migration state
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='plantationtype',
                    name='farms_plantationtype_crop_industry_code_unique',
                ),
                migrations.RemoveConstraint(
                    model_name='plantingmethod',
                    name='farms_plantingmethod_plantation_industry_code_unique',
                ),
            ],
        ),
    ]
