# Generated by Django 5.0.1 on 2026-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0013_plantationrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationrecord',
            name='grafting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantationrecord',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('drip', 'Drip'), ('flood', 'Flood')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plantationrecord',
            name='rootstock',
            field=models.CharField(blank=True, choices=[('dogridge', 'Dogridge'), ('bangalore', 'Bangalore'), ('polso', 'Polso')], max_length=30, null=True),
        ),
    ]
