# Generated by Django 5.0.1 on 2026-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_alter_plantationrecord_grafting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Size in acres', max_digits=10, null=True),
        ),
    ]
