# Generated by Django 5.0.1 on 2026-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0015_alter_farm_area_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationrecord',
            name='intercropping_crop_name',
            field=models.CharField(blank=True, help_text='Name of intercrop (only when intercropping=yes, Grapes only)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='plant_age',
            field=models.CharField(blank=True, choices=[('0_2', '0-2 years'), ('0_3', '0-3 years'), ('2_13', '2-13 years')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plantationrecord',
            name='rootstock',
            field=models.CharField(blank=True, choices=[('dogridge', 'Dogridge'), ('bangalore', 'Bangalore'), ('banglore', 'Banglore'), ('polso', 'Polso'), ('polson', 'Polson')], max_length=30, null=True),
        ),
    ]
