# Generated by Django 5.0.1 on 2025-12-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0017_add_industry_to_croptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='crop_variety',
            field=models.CharField(blank=True, help_text='Crop variety (e.g., Co 86032, Co 8371, etc.)', max_length=200, null=True),
        ),
    ]
