# Generated by Django 5.0.1 on 2025-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_assign_industry_to_existing_bookings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_status_233e96_idx',
            old_name='bookings_boo_status_8b5b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_booking_3ec655_idx',
            old_name='bookings_boo_bookin_0b4b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_start_d_3e8155_idx',
            old_name='bookings_boo_start_d_0b4b5a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_end_dat_f79cb7_idx',
            old_name='bookings_boo_end_dat_0b4b5a_idx',
        ),
    ]
