# Generated by Django 5.0.1 on 2025-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
